#!/bin/bash
set -e

echo "🎬 YYC³ AI Family - Docker 部署演示脚本"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⏱️  预计时长: 5 分钟"
echo "📋 演示内容: Docker 安装 → 配置 → 启动 → 验证 → 管理"
echo ""

echo "━━━ 第 1 段: Docker 环境确认 (0:00 - 0:30) ━━━"
echo ""
echo "🎤 旁白:"
echo "  '首先确认 Docker 和 Docker Compose 已安装。'"
echo ""
echo "🖥️ 画面: 终端执行"
echo ""

echo "  $ docker --version"
docker --version 2>/dev/null || echo "  Docker not found (录制时请确保已安装)"
echo ""

echo "  $ docker compose version"
docker compose version 2>/dev/null || echo "  Docker Compose not found"
echo ""

read -p "▶️ 按 Enter 继续..."

echo ""
echo "━━━ 第 2 段: 配置环境变量 (0:30 - 1:30) ━━━"
echo ""
echo "🎤 旁白:"
echo "  '安全第一！我们使用环境变量管理数据库密码。"
echo "  用 openssl 生成一个强密码。'"
echo ""
echo "🖥️ 画面: 终端执行"
echo ""

PASSWORD=$(openssl rand -base64 32 2>/dev/null || echo "demo-password-change-me")
echo "  $ openssl rand -base64 32"
echo "  ${PASSWORD}"
echo ""

echo "  $ export YYC3_PG_PASSWORD='${PASSWORD}'"
echo ""

echo "🎤 旁白:"
echo "  '密码已设置。接下来看看 docker-compose.yml 的配置。'"
echo ""
echo "🖥️ 画面: 打开 docker-compose.yml 展示三容器架构"
echo "  - yyc3-postgres: PostgreSQL 15"
echo "  - yyc3-proxy: Express API 代理"
echo "  - yyc3-frontend: Vite 前端开发"
echo ""
read -p "▶️ 按 Enter 继续..."

echo ""
echo "━━━ 第 3 段: 启动服务 (1:30 - 3:00) ━━━"
echo ""
echo "🎤 旁白:"
echo "  '一条命令启动全部服务！'"
echo ""
echo "🖥️ 画面: 终端执行"
echo ""

echo "  $ docker compose up -d --build"
echo "  # [+] Building..."
echo "  # [+] Running 3/3"
echo "  #  ✔ Network yyc3-network  Created"
echo "  #  ✔ Container yyc3-postgres  Started"
echo "  #  ✔ Container yyc3-proxy     Started"
echo "  #  ✔ Container yyc3-frontend  Started"
echo ""

echo "  $ docker compose ps"
echo "  # NAME              STATUS          PORTS"
echo "  # yyc3-postgres     Up (healthy)    0.0.0.0:5432->5432/tcp"
echo "  # yyc3-proxy        Up              0.0.0.0:3721->3721/tcp"
echo "  # yyc3-frontend     Up              0.0.0.0:5173->5173/tcp"
echo ""

echo "🎤 旁白:"
echo "  '三个容器全部启动成功！数据库健康检查也通过了。'"
echo ""
read -p "▶️ 按 Enter 继续..."

echo ""
echo "━━━ 第 4 段: 验证服务 (3:00 - 3:30) ━━━"
echo ""
echo "🎤 旁白:"
echo "  '让我们验证每个服务是否正常工作。'"
echo ""
echo "🖥️ 画面: 终端执行"
echo ""

echo "  # 验证 PostgreSQL"
echo "  $ docker exec yyc3-postgres pg_isready -U yyc3_admin"
echo "  # /var/run/postgresql:5432 - accepting connections"
echo ""

echo "  # 验证 API Proxy"
echo "  $ curl http://localhost:3721/health"
echo '  # {"status":"ok","uptime":42}'
echo ""

echo "  # 验证前端"
echo "  $ curl -s http://localhost:5173 | head -5"
echo "  # <!DOCTYPE html>..."
echo ""

echo "  # 查看日志"
echo "  $ docker compose logs --tail=5 yyc3-proxy"
echo ""

read -p "▶️ 按 Enter 继续..."

echo ""
echo "━━━ 第 5 段: 数据库操作 (3:30 - 4:00) ━━━"
echo ""
echo "🎤 旁白:"
echo "  '连接数据库查看数据。'"
echo ""
echo "🖥️ 画面: 终端执行"
echo ""

echo "  $ docker exec -it yyc3-postgres psql -U yyc3_admin -d yyc3_family"
echo "  # yyc3_family=# \\dt"
echo "  #            List of relations"
echo "  #  Schema | Name | Type  | Owner"
echo "  # --------+------+-------+-----------"
echo "  #  public | ...  | table | yyc3_admin"
echo ""

echo "  # 数据备份"
echo "  $ docker exec yyc3-postgres pg_dump -U yyc3_admin yyc3_family > backup.sql"
echo ""

read -p "▶️ 按 Enter 继续..."

echo ""
echo "━━━ 第 6 段: 管理命令和总结 (4:00 - 5:00) ━━━"
echo ""
echo "🎤 旁白:"
echo "  '最后看看常用的管理命令。'"
echo ""
echo "🖥️ 画面: 终端展示常用命令"
echo ""

echo "  # 查看实时日志"
echo "  $ docker compose logs -f"
echo ""

echo "  # 重启单个服务"
echo "  $ docker compose restart yyc3-proxy"
echo ""

echo "  # 停止所有服务"
echo "  $ docker compose down"
echo ""

echo "  # 停止并清除数据（谨慎！）"
echo "  $ docker compose down -v"
echo ""

echo "🎤 旁白:"
echo "  'Docker 部署就是这么简单！一条命令启动，"
echo "  环境一致、安全可靠。感谢观看！'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎬 Docker 部署演示脚本结束！"
echo ""
echo "📹 录制建议:"
echo "  - 使用终端录屏，确保字体清晰"
echo "  - docker compose up 过程可加速播放"
echo "  - 重点展示 docker compose ps 和健康检查"
echo "  - 数据库操作使用 psql 交互界面更直观"
