#!/bin/bash
set -e

echo "🎬 YYC³ AI Family - 5 分钟快速开始演示脚本"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⏱️  预计时长: 5 分钟"
echo "📋 演示内容: 环境搭建 → 安装 → 启动 → 功能展示"
echo ""

echo "━━━ 第 1 段: 项目介绍 (0:00 - 0:30) ━━━"
echo ""
echo "🎤 旁白:"
echo "  '大家好，欢迎来到 YYC³ AI Family 项目。"
echo "  这是一个基于 React 18 + TypeScript + Vite 5 的"
echo "  AI 智能家族系统，支持多模型对话、工作流管理、"
echo "  GitHub 集成等核心功能。'"
echo ""
echo "🖥️ 画面:"
echo "  1. 打开 GitHub 仓库页面"
echo "  2. 展示 README.md 项目介绍"
echo "  3. 展示技术栈和架构图"
echo ""
read -p "▶️ 按 Enter 继续下一段..."

echo ""
echo "━━━ 第 2 段: 环境准备 (0:30 - 1:30) ━━━"
echo ""
echo "🎤 旁白:"
echo "  '首先确认环境。需要 Node.js 18+、pnpm 8+ 和 Git。'"
echo ""
echo "🖥️ 画面: 打开终端，执行以下命令"
echo ""

echo "  $ node --version"
node --version
echo ""
echo "  $ pnpm --version"
pnpm --version
echo ""
echo "  $ git --version"
git --version
echo ""

echo "🎤 旁白:"
echo "  '环境确认完毕，接下来克隆项目。'"
echo ""
read -p "▶️ 按 Enter 继续下一段..."

echo ""
echo "━━━ 第 3 段: 安装和启动 (1:30 - 2:30) ━━━"
echo ""
echo "🖥️ 画面: 终端中执行安装和启动"
echo ""

echo "  $ pnpm install"
echo "  # (展示安装过程...)"
echo ""

echo "  $ pnpm dev"
echo "  # VITE v5.x.x  ready in xxx ms"
echo "  # ➜  Local:   http://localhost:5173/"
echo ""

echo "🎤 旁白:"
echo "  '三步就搞定了！pnpm install 安装依赖，pnpm dev 启动开发服务器。"
echo "  现在打开浏览器访问 localhost:5173。'"
echo ""
read -p "▶️ 按 Enter 继续下一段..."

echo ""
echo "━━━ 第 4 段: 功能展示 (2:30 - 4:00) ━━━"
echo ""
echo "🎤 旁白:"
echo "  '让我们看看核心功能。'"
echo ""
echo "🖥️ 画面: 浏览器中展示以下功能"
echo ""
echo "  1️⃣  AI 聊天界面"
echo "     - 展示聊天组件"
echo "     - 输入一条消息，展示 AI 响应"
echo "     - 展示流式输出效果"
echo ""
echo "  2️⃣  多频道管理"
echo "     - 创建新频道"
echo "     - 切换频道"
echo "     - 展示频道列表"
echo ""
echo "  3️⃣  工作流面板"
echo "     - 展示看板视图"
echo "     - 拖拽卡片演示"
echo "     - 展示状态流转"
echo ""
echo "  4️⃣  设置面板"
echo "     - AI 模型切换"
echo "     - 主题切换（亮/暗模式）"
echo "     - 语言切换（展示 10 国语言）"
echo ""
read -p "▶️ 按 Enter 继续下一段..."

echo ""
echo "━━━ 第 5 段: 质量检查 (4:00 - 4:30) ━━━"
echo ""
echo "🎤 旁白:"
echo "  '项目内置了完整的质量检查工具链。'"
echo ""
echo "🖥️ 画面: 终端执行以下命令"
echo ""

echo "  $ pnpm typecheck    # TypeScript 类型检查"
echo "  $ pnpm lint         # ESLint 代码检查"
echo "  $ pnpm test --run   # 运行测试"
echo "  $ pnpm build        # 生产构建"
echo ""

echo "🎤 旁白:"
echo "  '所有检查通过，代码质量有保障。'"
echo ""
read -p "▶️ 按 Enter 继续下一段..."

echo ""
echo "━━━ 第 6 段: 总结和号召 (4:30 - 5:00) ━━━"
echo ""
echo "🎤 旁白:"
echo "  'YYC³ AI Family 开箱即用，三步即可启动。"
echo "  支持 Docker 部署、CI/CD 自动化、完整的文档体系。"
echo "  欢迎加入我们，给项目一个 Star！'"
echo ""
echo "🖥️ 画面:"
echo "  1. 展示 GitHub Star 按钮"
echo "  2. 展示文档站点 (docs-site)"
echo "  3. 结束画面 + 项目 Logo"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎬 演示脚本结束！"
echo ""
echo "📹 录制建议:"
echo "  - 使用 OBS Studio 或 Screen Studio 录制"
echo "  - 终端使用深色主题，字体大小 ≥ 18px"
echo "  - 浏览器窗口大小: 1920x1080 或 1440x900"
echo "  - 使用 macOS 截图快捷键 Cmd+Shift+5 录屏"
